export const QUESTIONS = [
  "Nombra una comida tradicional de Navidad",
  "Nombra un país europeo",
  "Nombra una fruta roja",
  "Nombra un deporte olímpico",
  "Nombra un color del arcoíris",
  "Nombra una película de Disney",
  "Nombra un animal de granja",
  "Nombra una profesión relacionada con la salud",
  "Nombra un día festivo",
  "Nombra una marca de coches",
  "Nombra un instrumento musical",
  "Nombra una ciudad española",
  "Nombra un superhéroe",
  "Nombra un electrodoméstico de cocina",
  "Nombra una red social",
  "Nombra un país de América del Sur",
  "Nombra un postre típico",
  "Nombra una parte del cuerpo",
  "Nombra un programa de televisión",
  "Nombra una estación del año",
  "Nombra un animal marino",
  "Nombra una bebida caliente",
  "Nombra un tipo de música",
  "Nombra una película de terror",
  "Nombra un juego de mesa",
  "Nombra una verdura verde",
  "Nombra una prenda de vestir",
  "Nombra un medio de transporte",
  "Nombra una mascota común",
  "Nombra un país asiático",
  "Nombra una bebida alcohólica",
  "Nombra un héroe de videojuego",
  "Nombra un tipo de pan",
  "Nombra una flor",
  "Nombra un idioma",
  "Nombra una profesión relacionada con la educación",
  "Nombra un planeta del sistema solar",
  "Nombra un sabor de helado",
  "Nombra una película de Pixar",
  "Nombra un tipo de árbol",
  "Nombra una serie de Netflix",
  "Nombra una capital europea",
  "Nombra un tipo de queso",
  "Nombra un cantante famoso",
  "Nombra un deporte de equipo",
  "Nombra una comida rápida",
  "Nombra una marca de ropa",
  "Nombra un objeto que encuentras en un baño",
  "Nombra una emoción",
  "Nombra un tipo de zapato"
];
