export const QUESTIONS = [
    "Nombra una comida tradicional de Navidad",
    "Nombra un país europeo",
    "Nombra una fruta roja",
    "Nombra un deporte olímpico",
    "Nombra un color del arcoíris",
    "Nombra una película de Disney",
    "Nombra un animal de granja",
    "Nombra una profesión relacionada con la salud",
    "Nombra un día festivo",
    "Nombra una marca de coches",
    "Nombra un instrumento musical",
    "Nombra una ciudad española",
    "Nombra un superhéroe",
    "Nombra un electrodoméstico de cocina",
    "Nombra una red social",
    "Nombra un país de América del Sur",
    "Nombra un postre típico",
    "Nombra una parte del cuerpo",
    "Nombra un programa de televisión",
    "Nombra una estación del año",
    "Nombra un animal marino",
    "Nombra una bebida caliente",
    "Nombra un tipo de música",
    "Nombra una película de terror",
    "Nombra un juego de mesa",
    "Nombra una verdura verde",
    "Nombra una prenda de vestir",
    "Nombra un medio de transporte",
    "Nombra una mascota común",
    "Nombra un país asiático",
    "Nombra una bebida alcohólica",
    "Nombra un héroe de videojuego",
    "Nombra un tipo de pan",
    "Nombra una flor",
    "Nombra un idioma",
    "Nombra una profesión relacionada con la educación",
    "Nombra un planeta del sistema solar",
    "Nombra un sabor de helado",
    "Nombra una película de Pixar",
    "Nombra un tipo de árbol",
    "Nombra una serie de Netflix",
    "Nombra una capital europea",
    "Nombra un tipo de queso",
    "Nombra un cantante famoso",
    "Nombra un deporte de equipo",
    "Nombra una comida rápida",
    "Nombra una marca de ropa",
    "Nombra un objeto que encuentras en un baño",
    "Nombra una emoción",
    "Nombra un tipo de zapato",
    "Nombra un ingrediente para una hamburguesa",
    "Nombra algo que siempre llevas en la cartera o billetera",
    "Nombra un animal que tenga cuernos",
    "Nombra algo que la gente suele comprar cuando se independiza",
    "Nombra un objeto que sea muy pesado",
    "Nombra una excusa típica para no ir al gimnasio",
    "Nombra un sabor de mermelada",
    "Nombra una parte de una planta",
    "Nombra algo que encontrarías en un casino",
    "Nombra un objeto que usas para medir algo",
    "Nombra un personaje famoso que sea calvo",
    "Nombra algo que se suele hacer en una boda",
    "Nombra el peor olor que puedes imaginar",
    "Nombra una marca de refresco de cola",
    "Nombra un animal prehistórico",
    "Nombra algo que se suele desayunar en un hotel",
    "Nombra una ciudad famosa por su torre o monumento",
    "Nombra algo que nunca falta en un botiquín",
    "Nombra un color de ojos",
    "Nombra un objeto que tenga cristales o lentes",
    "Nombra una actividad que se hace en la nieve",
    "Nombra un ingrediente de la ensaladilla rusa",
    "Nombra un insecto que la gente odie",
    "Nombra un tipo de calzado que no sea para hacer deporte",
    "Nombra el regalo más típico en San Valentín",
    "Nombra algo que se pueda encontrar debajo de la cama",
    "Nombra un electrodoméstico que hace mucho ruido",
    "Nombra un animal que asocies con la mala suerte",
    "Nombra algo que se vende en una papelería",
    "Nombra un desierto famoso",
    "Nombra una asignatura difícil del colegio",
    "Nombra una marca de teléfonos móviles",
    "Nombra un objeto que se usa para pescar",
    "Nombra lo primero que haces al subir a un coche",
    "Nombra una fruta que tenga que pelarse",
    "Nombra algo que la gente colecciona",
    "Nombra el animal más rápido que conoces",
    "Nombra un tipo de salsa para la pasta",
    "Nombra algo que se ve en el cielo de noche",
    "Nombra una profesión que requiere llevar uniforme",
    "Nombra un deporte que se juegue en una cancha",
    "Nombra una película que transcurra en el espacio",
    "Nombra el ingrediente principal de una tortilla",
    "Nombra algo que se suele guardar en el garaje",
    "Nombra un animal que hiberna",
    "Nombra un objeto que encontrarías en la mochila de un niño",
    "Nombra una marca de leche",
    "Nombra algo que cause alergia a muchas personas",
    "Nombra el instrumento más importante de una orquesta",
    "Nombra un país famoso por su café",
    "Nombra un objeto inflable",
    "Nombra algo que harías si te tocara la lotería",
    "Nombra una criatura mitológica",
    "Nombra algo que se use para decorar en Navidad",
    "Nombra el animal más inteligente después del humano",
    "Nombra una prenda de ropa que se use solo en invierno",
    "Nombra algo que se compra por docenas",
    "Nombra una parte del cuerpo que te duele a menudo",
    "Nombra un objeto que tenga cables",
    "Nombra un buscador de internet",
    "Nombra la carne que más se consume",
    "Nombra algo que encontrarías en un museo",
    "Nombra una flor que no sea una rosa",
    "Nombra una actividad que te relaja",
    "Nombra un villano de Disney",
    "Nombra un material de construcción",
    "Nombra un sabor de chicle",
    "Nombra algo que se hace antes de dormir",
    "Nombra un animal que vive en el desierto",
    "Nombra un objeto esencial para un fotógrafo",
    "Nombra una ciudad que nunca duerme",
    "Nombra algo que se pone encima de la mesa",
    "Nombra un fenómeno meteorológico peligroso",
    "Nombra un tipo de moneda extranjera",
    "Nombra un objeto que se usa para coser",
    "Nombra el mejor amigo del hombre",
    "Nombra una hortaliza de color naranja",
    "Nombra algo que uses para peinarte",
    "Nombra un juego de cartas popular",
    "Nombra un lugar donde se necesite entrada para pasar",
    "Nombra un ingrediente de una pizza",
    "Nombra algo que se encuentra en un parque de atracciones",
    "Nombra un personaje de Los Simpson",
    "Nombra una excusa común para llegar tarde",
    "Nombra algo que haces nada más despertarte",
    "Nombra un animal que sea ruidoso",
    "Nombra una asignatura del colegio",
    "Nombra un villano de película",
    "Nombra algo que se compra en una panadería",
    "Nombra un lugar donde hace mucho frío",
    "Nombra un objeto que guardas en la mesita de noche",
    "Nombra un deporte que no use una pelota",
    "Nombra una aplicación del móvil que uses a diario",
    "Nombra un regalo común de cumpleaños",
    "Nombra un animal que no podrías tener como mascota",
    "Nombra un sabor de patatas fritas de bolsa",
    "Nombra una parte del coche",
    "Nombra algo que te da miedo",
    "Nombra un actor o actriz de Hollywood",
    "Nombra una fruta que tenga semillas grandes",
    "Nombra algo que haces en una primera cita",
    "Nombra un objeto que llevas a la playa",
    "Nombra un animal muy lento",
    "Nombra un topping para un helado",
    "Nombra una herramienta de bricolaje",
    "Nombra algo que se encuentra en una oficina",
    "Nombra una ciudad famosa por su comida",
    "Nombra un tipo de clima",
    "Nombra una princesa de Disney",
    "Nombra algo que huela muy bien",
    "Nombra un objeto que se usa para escribir",
    "Nombra un hábito molesto de otras personas",
    "Nombra una forma de cocinar huevos",
    "Nombra un superhéroe que use capa",
    "Nombra un animal que vive en la selva",
    "Nombra algo que se pone en una ensalada",
    "Nombra una tarea del hogar que odies hacer",
    "Nombra un género de cine",
    "Nombra algo que siempre olvidas llevar contigo",
    "Nombra un instrumento de cuerda",
    "Nombra una bebida que se sirva con hielo",
    "Nombra un objeto de color amarillo",
    "Nombra un animal que se desplace saltando",
    "Nombra una red social de fotografía o vídeo",
    "Nombra algo que compras en el cine",
    "Nombra un mes del año que sea caluroso",
    "Nombra un personaje de cuentos infantiles",
    "Nombra algo que se encuentra en un gimnasio",
    "Nombra una festividad donde se den regalos",
    "Nombra un tipo de calzado deportivo",
    "Nombra algo que se puede hacer en un avión",
    "Nombra un animal con manchas",
    "Nombra una serie de dibujos animados",
    "Nombra algo que se usa para limpiar el suelo",
    "Nombra un ingrediente esencial para hacer un pastel",
    "Nombra un lugar donde se susurra",
    "Nombra un tipo de carne",
    "Nombra una actividad que haces un domingo",
    "Nombra un fenómeno natural",
    "Nombra un objeto que tenga botones",
    "Nombra un animal que vuele",
    "Nombra una fruta cítrica",
    "Nombra algo que se hace en una fiesta",
    "Nombra un idioma que suene romántico",
    "Nombra una parte de la cara",
    "Nombra un mueble del salón",
    "Nombra un personaje de Star Wars",
    "Nombra algo que se rellena con aire",
    "Nombra un tipo de pasta",
    "Nombra un objeto que se usa cuando llueve"
];
